"""The names the data actually uses, for the prompt to quote verbatim.

Zones, statuses, cargo types and ports are matched lexically, so the model has to
spell them exactly as stored. Cells are comma-joined, and a few ports come as slash
pairs such as ``Itaguai / Sepetiba``, so every column is split on both before the
distinct set is taken. The search itself splits on the comma only and matches a
port inside its element, so either half of a pair finds the row.

Generated by ``python -m ai_platform.backend.vocabulary`` after each pipeline
reload and committed beside this module; ``prompts`` reads it at import. Ports
are one list because the same name can appear as a load port, a discharge port
or an open area.
"""

from __future__ import annotations

import asyncio
import json
from pathlib import Path

from ai_platform.backend.db import fetch_rows

VOCABULARY_PATH = Path(__file__).with_name("vocabulary.json")

GROUPS: dict[str, tuple[tuple[str, str], ...]] = {
    "zones": (
        ("order_test", "load_zone"),
        ("order_test", "discharge_parent_zone"),
        ("tonnage_test", "parent_zone"),
    ),
    "statuses": (("tonnage_test", "vessel_status"),),
    "cargo_types": (("order_test", "cargo_type"),),
    "ports": (
        ("order_test", "load_port"),
        ("order_test", "discharge_port"),
        ("tonnage_test", "open_area"),
    ),
}


async def collect() -> dict[str, list[str]]:
    """Read the distinct comma-separated elements of every column, per group.

    Returns
    -------
    dict of str to list of str
        Group name to sorted names.
    """
    vocabulary: dict[str, list[str]] = {}
    for group, columns in GROUPS.items():
        names: set[str] = set()
        for table, column in columns:
            rows = await fetch_rows(
                f"SELECT DISTINCT trim(element) AS name "
                f"FROM public.{table}, "
                f"unnest(regexp_split_to_array({column}, ', | / ')) AS element "
                f"WHERE {column} IS NOT NULL AND trim(element) <> ''",
                [],
            )
            names.update(row["name"] for row in rows)
        vocabulary[group] = sorted(names)
    return vocabulary


async def write() -> None:
    """Regenerate ``vocabulary.json`` from the database.

    Returns
    -------
    None
    """
    vocabulary = await collect()
    VOCABULARY_PATH.write_text(
        json.dumps(vocabulary, indent=1, ensure_ascii=False) + "\n", encoding="utf-8"
    )


def load() -> dict[str, list[str]]:
    """Read the committed vocabulary.

    Returns
    -------
    dict of str to list of str
        Group name to names, as written by :func:`write`.

    Raises
    ------
    FileNotFoundError
        If the file has not been generated.
    """
    if not VOCABULARY_PATH.exists():
        raise FileNotFoundError(
            f"{VOCABULARY_PATH} is missing. Generate it with "
            "`uv run python -m ai_platform.backend.vocabulary`."
        )
    return json.loads(VOCABULARY_PATH.read_text(encoding="utf-8"))


if __name__ == "__main__":
    asyncio.run(write())
